from PyQt5 import QtCore, QtGui, QtWidgets


class MainWindow(QtWidgets.QWidget):
    def __init__(self, window_class=None):
        super().__init__()
        self.appearance = self.palette()
        self.central_widget = QtWidgets.QWidget(window_class)
        self.status_bar = QtWidgets.QStatusBar(window_class)
        self.menu_bar = QtWidgets.QMenuBar(window_class)
        self.label_path = QtWidgets.QLabel(self.central_widget)
        self.label_result = QtWidgets.QLabel(self.central_widget)
        self.push_browse = QtWidgets.QPushButton(self.central_widget)
        self.label = QtWidgets.QLabel(self.central_widget)
        self.label_pic = QtWidgets.QLabel(self.central_widget)
        self.pushRecognize = QtWidgets.QPushButton(self.central_widget)

    def setup_ui(self, window_class):
        window_class.setObjectName("main_window")
        window_class.resize(685, 600)
        window_class.setMinimumSize(QtCore.QSize(685, 600))
        self.central_widget.setObjectName("central_widget")
        self.pushRecognize.setGeometry(QtCore.QRect(20, 510, 641, 21))
        self.pushRecognize.setObjectName("push_recognize")
        self.label_pic.setGeometry(QtCore.QRect(20, 50, 150, 150))
        self.label_pic.setMinimumSize(QtCore.QSize(281, 381))
        self.label_pic.setMaximumSize(QtCore.QSize(281, 381))
        self.label_pic.setFrameShape(QtWidgets.QFrame.Box)
        self.label_pic.setText("")
        self.label_pic.setObjectName("label_pic")
        self.label.setGeometry(QtCore.QRect(50, 10, 600, 13))
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(size_policy)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.push_browse.setGeometry(QtCore.QRect(580, 460, 75, 23))
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.push_browse.sizePolicy().hasHeightForWidth())
        self.push_browse.setSizePolicy(size_policy)
        self.push_browse.setMinimumSize(QtCore.QSize(75, 23))
        self.push_browse.setObjectName("push_browse")
        self.label_result.setGeometry(QtCore.QRect(380, 50, 150, 150))
        self.label_result.setMinimumSize(QtCore.QSize(281, 381))
        self.label_result.setMaximumSize(QtCore.QSize(281, 381))
        font = QtGui.QFont()
        font.setFamily("Candelas Medium")
        font.setPointSize(16)
        self.label_result.setFont(font)
        self.label_result.setFrameShape(QtWidgets.QFrame.Box)
        self.label_result.setText("")
        self.label_result.setAlignment(QtCore.Qt.AlignCenter)
        self.label_result.setObjectName("label_result")
        self.label_path.setGeometry(QtCore.QRect(30, 460, 541, 16))
        self.label_path.setText("")
        self.label_path.setObjectName("label_path")
        window_class.setCentralWidget(self.central_widget)
        self.menu_bar.setGeometry(QtCore.QRect(0, 0, 685, 21))
        self.menu_bar.setObjectName("menu_bar")
        window_class.setMenuBar(self.menu_bar)
        self.status_bar.setObjectName("status_bar")
        window_class.setStatusBar(self.status_bar)

        self.retranslate_ui(window_class)
        QtCore.QMetaObject.connectSlotsByName(window_class)

    def retranslate_ui(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "main_window"))
        self.pushRecognize.setText(_translate("main_window", "Recognize"))
        self.label.setText(_translate("main_window",
                                      "Set the path to the image and click \"Recognize\""))
        self.push_browse.setText(_translate("main_window", "Add..."))
